# Generated by Django 3.0.4 on 2020-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
        ),
    ]
