# Generated by Django 3.0.8 on 2020-07-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20200711_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
    ]
